# Generated by Django 3.0.3 on 2020-02-25 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblogapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='note_body',
            new_name='notebody',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='note_time',
            new_name='notetime',
        ),
    ]
