# Generated by Django 3.0.3 on 2020-02-25 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblogapp', '0002_auto_20200225_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='notebody',
            new_name='note_body',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='notetime',
            new_name='note_time',
        ),
    ]
